definitions:
  blockhttp.Response:
    type: object
  gin.H:
    additionalProperties: true
    type: object
info:
  contact: {}
  license: {}
paths:
  /BlockChain:
    post:
      description: 用于同步本地区块链数据
      responses:
        "200":
          description: statuc":"ok", "data":"bytesdata"}
          schema:
            $ref: '#/definitions/gin.H'
      summary: 当前区块链数据
      tags:
      - 服务器组
  /balance:
    get:
      description: 返回指定用户的余额信息
      parameters:
      - description: Ivan
        in: query
        name: address
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockhttp.Response'
      summary: 余额
      tags:
      - 前端
  /balancedetailed:
    get:
      description: 返回指定地址的交易明细
      parameters:
      - description: Ivan
        in: query
        name: address
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 余额明细
      tags:
      - 前端
  /entry:
    post:
      description: 生产茶叶数据， 用于交易
      parameters:
      - description: Ivan
        in: formData
        name: address
        required: true
        type: string
      responses:
        "200":
          description: statuc":"ok", "data":""}
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: statuc":"error", "message":"失败原因"}
          schema:
            $ref: '#/definitions/gin.H'
      summary: 数据录入
      tags:
      - 前端
  /registerinfo:
    get:
      description: 返回指当前所有的注册信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 返回注册信息
      tags:
      - 服务端
  /teadata:
    post:
      description: 获取指定地址的茶叶数据
      parameters:
      - description: ASHASDSABDKJQWFKJBASFKAF
        in: formData
        name: address
        required: true
        type: string
      responses:
        "200":
          description: statuc":"ok", "data":""}
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: statuc":"error", "message":"失败原因"}
          schema:
            $ref: '#/definitions/gin.H'
      summary: 茶叶数据
      tags:
      - 前端
  /transaction:
    post:
      description: 用于两个不同地址之间的数据交易
      parameters:
      - description: Ivan
        in: formData
        name: address
        required: true
        type: string
      responses:
        "200":
          description: statuc":"ok", "data":"bytesdata"}
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: statuc":"error", "message":"失败原因"}
          schema:
            $ref: '#/definitions/gin.H'
      summary: 茶叶交易
      tags:
      - 前端
  /version:
    get:
      description: 返回当前区块链长度
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 区块链版本
      tags:
      - 前端
swagger: "2.0"
