definitions:
  blockhttp.Response:
    type: object
  gin.H:
    additionalProperties: true
    type: object
info:
  contact: {}
  license: {}
paths:
  /BlockChain:
    post:
      description: 用于同步本地区块链数据
      responses:
        "200":
          description: statuc":"ok", "data":"bytesdata"}
          schema:
            $ref: '#/definitions/gin.H'
      summary: 当前区块链数据
      tags:
      - 服务器组
  /balance:
    get:
      description: 返回指定用户的余额信息
      parameters:
      - description: Ivan
        in: query
        name: address
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockhttp.Response'
      summary: 余额
      tags:
      - 前端
  /show:
    get:
      description: 返回当前区块链长度
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 区块链版本
      tags:
      - 前端
  /version:
    get:
      description: 返回当前区块链长度
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 区块链版本
      tags:
      - 前端
swagger: "2.0"
